### ISSUE TITLE
 Improve Visibility of Invalid Port Number Warning Message

### ISSUE THREAD

**Issue by noejunior792** [euotiniel/og-local#5]
The current UI for displaying the warning message when an invalid port number is entered is not highly visible. The yellow warning text blends into the background and may negatively impact user experience. A more noticeable and user-friendly design is needed for this warning message.

1 - Open the application.
2 - Enter an invalid port number in the input field.
3 - Click the "Check Port" button.

Expected Result:
The warning message should be highly visible and catch the user's attention immediately.

Actual Result:
The warning message in yellow is not very noticeable, making it difficult for users to see the feedback.
![Captura de ecrã 2024-08-05 000838](https://github.com/user-attachments/assets/5e856c14-d857-4434-bc06-d723d430eb76)

**Comment by euotiniel** [comment]
Can you move up a PR with this change?

**Comment by noejunior792** [comment]
Of course.
